scrape_configs:
  - job_name: 'workflowEngineInstanz'
    scrape_interval: 2s
    metrics_path: '/actuator/prometheus' ##prometheus endpoint
    static_configs:
      - targets: ['workflowEngineInstanz:8080'] ## host and port for your mis
