resilience4j.retry:
  instances:
    fetchStatusRetry:
      maxRetryAttempts: 5
      waitDuration: 2s

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: {EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true