version: "3.9"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      app-tier:
        ipv4_address: 10.0.4.10
  kafka:
      image: docker.io/bitnami/kafka:3.2
      ports:
        - "9092:9092"
      volumes:
        - "kafka_data:/bitnami"
      environment:
        - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
        - ALLOW_PLAINTEXT_LISTENER=yes
      depends_on:
        - zookeeper
      networks:
        app-tier:
          ipv4_address: 10.0.4.2

  fluidAnalyserInstanz:
      image: wirschiffendas/fluidanalyser
      depends_on:
        - workflowEngineInstanz
      networks:
        app-tier:
          ipv4_address: 10.0.4.5
  workflowEngineInstanz:
      image: wirschiffendas/workflowengine
      depends_on:
        - backendforfrontendInstanz
      networks:
        app-tier:
          ipv4_address: 10.0.4.4
  coolingsystemAnalyserInstanz:
      image: wirschiffendas/coolingsystemanalyser
      depends_on:
        - workflowEngineInstanz
      networks:
        app-tier:
          ipv4_address: 10.0.4.6
  powertransmissionAnalyserInstanz:
      image: wirschiffendas/powertransmissionanalyser
      depends_on:
        - workflowEngineInstanz
      networks:
        app-tier:
          ipv4_address: 10.0.4.7
  startingelementsAnalyserInstanz:
      image: wirschiffendas/startingelementsanalyser
      depends_on:
        - workflowEngineInstanz
      networks:
          app-tier:
            ipv4_address: 10.0.4.8

  backendforfrontendInstanz:
      image: wirschiffendas/backendforfrontend
      networks:
        app-tier:
          ipv4_address: 10.0.4.3

networks:
  app-tier:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.4.0/24
volumes:
    zookeeper_data:
      driver: local
    kafka_data:
      driver: local

